name = "Create 2022"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10727ba4e12b90eaedf4f722da53256b5e98a8e20b7c549ea49fc7a4d66eeb1c"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
