name = "Create 2022"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed788c521c817991aa5a2ebd1b3548326f5dde95fc3a194e0eb0dc3ce3b7da39"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
