name = "Create 2022"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fed54abcc5c4e4fcf775a72c27370bb056fe913905bc5ac94a2f5b0edf2bdf5"

[versions]
forge = "39.0.36"
minecraft = "1.18.1"
