name = "Create 2022"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce2b4b3ea61947d648283c1b5c9b7ca2fd78ef3e47d17bbbb3467a86d08a506a"

[versions]
forge = "39.0.45"
minecraft = "1.18.1"
