name = "Create 2022"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b41d908ffdbd2dee6a5f30ff9ca84ad1883b21f0f03efc781c650002cafb5b1"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
