name = "Advanced Chimneys"
filename = "AdChimneys-1.18.2-8.3.1.0-build.1034.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "19bade5652fa22a422a564d36cd7a12464ff5115"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3905427
project-id = 244830
