name = "Advanced Chimneys"
filename = "AdChimneys-1.18.2-8.3.0.0-build.1016.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "11a7384dc5dc862f21be8d1b736b606d5e8f57b6"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3864196
project-id = 244830
