name = "Advanced Peripherals"
filename = "advancedperipherals-1.18.1-0.7.9r.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3624/652/advancedperipherals-1.18.1-0.7.9r.jar"
hash-format = "murmur2"
hash = "3667662091"

[update]
[update.curseforge]
file-id = 3624652
project-id = 431725
