name = "Advanced Peripherals"
filename = "advancedperipherals-1.18.1-0.7.8.1r.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3579/355/advancedperipherals-1.18.1-0.7.8.1r.jar"
hash-format = "murmur2"
hash = "3200618814"

[update]
[update.curseforge]
file-id = 3579355
project-id = 431725
