name = "AI Improvements"
filename = "AI-Improvements-1.18-0.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3543/562/AI-Improvements-1.18-0.4.0.jar"
hash-format = "murmur2"
hash = "1822903046"

[update]
[update.curseforge]
file-id = 3543562
project-id = 233019
