name = "Architectury API (Forge)"
filename = "architectury-3.6.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3632/976/architectury-3.6.15.jar"
hash-format = "murmur2"
hash = "386419961"

[update]
[update.curseforge]
file-id = 3632976
project-id = 419699
