name = "Architectury API (Fabric/Forge)"
filename = "architectury-4.8.79-forge.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "9787c3f5c1afc6710190260b84e99d562b6fc2e5"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3923093
project-id = 419699
