name = "Balm (Forge Edition)"
filename = "balm-2.4.2+0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/241/balm-2.4.2+0.jar"
hash-format = "murmur2"
hash = "2487353952"

[update]
[update.curseforge]
file-id = 3630241
project-id = 531761
