name = "BetterF3"
filename = "BetterF3-1.2.2-Forge-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3551/266/BetterF3-1.2.2-Forge-1.18.jar"
hash-format = "murmur2"
hash = "1924472981"

[update]
[update.curseforge]
file-id = 3551266
project-id = 401648
