name = "Bow Infinity Fix (Forge/Fabric)"
filename = "BowInfinityFix-1.18.x-rv11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/224/BowInfinityFix-1.18.x-rv11.jar"
hash-format = "murmur2"
hash = "809388299"

[update]
[update.curseforge]
file-id = 3546224
project-id = 224713
