name = "Builders Crafts & Additions (Forge)"
filename = "buildersaddition-1.18.1-20220123a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3620/249/buildersaddition-1.18.1-20220123a.jar"
hash-format = "murmur2"
hash = "3200424169"

[update]
[update.curseforge]
file-id = 3620249
project-id = 389697
