name = "Builders Crafts & Additions (Forge)"
filename = "buildersaddition-1.18-20211208a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3554/342/buildersaddition-1.18-20211208a.jar"
hash-format = "murmur2"
hash = "773338877"

[update]
[update.curseforge]
file-id = 3554342
project-id = 389697
