name = "Carry On"
filename = "carryon-1.18.1-1.17.0.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3601/938/carryon-1.18.1-1.17.0.7.jar"
hash-format = "murmur2"
hash = "3616957891"

[update]
[update.curseforge]
file-id = 3601938
project-id = 274259
