name = "Chisels & Bits - For Forge"
filename = "ChiselsBits-forge-1.18.1-1.2.77-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3609/458/ChiselsBits-forge-1.18.1-1.2.77-universal.jar"
hash-format = "murmur2"
hash = "2525468966"

[update]
[update.curseforge]
file-id = 3609458
project-id = 231095
