name = "Chisels & Bits - For Forge"
filename = "ChiselsBits-forge-1.18.1-1.2.76-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3608/730/ChiselsBits-forge-1.18.1-1.2.76-universal.jar"
hash-format = "murmur2"
hash = "121204306"

[update]
[update.curseforge]
file-id = 3608730
project-id = 231095
