name = "Clickable advancements[Forge/Fabric]"
filename = "clickadv-1.18-2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3548/770/clickadv-1.18-2.0.jar"
hash-format = "murmur2"
hash = "1823146574"

[update]
[update.curseforge]
file-id = 3548770
project-id = 511733
