name = "Cloth Config API (Forge)"
filename = "cloth-config-6.1.50-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3608/26/cloth-config-6.1.50-forge.jar"
hash-format = "murmur2"
hash = "489419113"

[update]
[update.curseforge]
file-id = 3608026
project-id = 348521
