name = "Controlling"
filename = "Controlling-forge-1.18.1-9.0+13.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3617/169/Controlling-forge-1.18.1-9.0+13.jar"
hash-format = "murmur2"
hash = "3007703502"

[update]
[update.curseforge]
file-id = 3617169
project-id = 250398
