name = "Controlling"
filename = "Controlling-forge-1.18.1-9.0.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/14/Controlling-forge-1.18.1-9.0.11.jar"
hash-format = "murmur2"
hash = "2395729960"

[update]
[update.curseforge]
file-id = 3599014
project-id = 250398
