name = "Corpse"
filename = "corpse-1.18.1-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3602/236/corpse-1.18.1-1.0.2.jar"
hash-format = "murmur2"
hash = "3801135408"

[update]
[update.curseforge]
file-id = 3602236
project-id = 316582
