name = "Create Deco"
filename = "createdeco-1.2.8-1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "75bdc0a45837d7726fddb9de5a3de6f92cd3e072"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3866123
project-id = 509285
