name = "Create Chunkloading"
filename = "createchunkloading-1.2.0-forge.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "b0a128cf94470de700bbe20ab875ca58064715ae"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3872038
project-id = 494206
