name = "Create Deco"
filename = "createdeco-1.2.4-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/347/createdeco-1.2.4-1.18.jar"
hash-format = "murmur2"
hash = "2457940836"

[update]
[update.curseforge]
file-id = 3631347
project-id = 509285
