name = "Create Deco"
filename = "createdeco-1.2.3-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3609/153/createdeco-1.2.3-1.18.jar"
hash-format = "murmur2"
hash = "4198433729"

[update]
[update.curseforge]
file-id = 3609153
project-id = 509285
