name = "Curio of Undying (Forge)"
filename = "curioofundying-forge-1.18-5.3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3553/486/curioofundying-forge-1.18-5.3.0.0.jar"
hash-format = "murmur2"
hash = "3020868334"

[update]
[update.curseforge]
file-id = 3553486
project-id = 316873
