name = "Decorative Blocks"
filename = "Decorative Blocks-forge-1.18.1-2.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/621/Decorative Blocks-forge-1.18.1-2.0.4.jar"
hash-format = "murmur2"
hash = "474270441"

[update]
[update.curseforge]
file-id = 3613621
project-id = 362528
