name = "Effective (Forge)"
filename = "effective_for_forge-1.001.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/266/effective_for_forge-1.001.jar"
hash-format = "murmur2"
hash = "3006675011"

[update]
[update.curseforge]
file-id = 3575266
project-id = 557796
