name = "FancyMenu [Forge]"
filename = "fancymenu_forge_2.6.1_MC_1.18-1.18.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3631/907/fancymenu_forge_2.6.1_MC_1.18-1.18.1.jar"
hash-format = "murmur2"
hash = "1648781467"

[update]
[update.curseforge]
file-id = 3631907
project-id = 367706
