name = "FancyMenu [Forge]"
filename = "fancymenu_forge_2.11.1_MC_1.18.2.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "fb5f20d8c946a725fc9f15a1a01a340418d1cb5a"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3891585
project-id = 367706
