name = "FancyMenu [Forge]"
filename = "fancymenu_forge_2.12.0_MC_1.18.2.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "97c0eeb3fa47eb0d93bc59ba3065a356a3e56b83"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3913050
project-id = 367706
