name = "Farmer's Delight"
filename = "FarmersDelight-1.18.1-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/226/FarmersDelight-1.18.1-1.0.1.jar"
hash-format = "murmur2"
hash = "1858980922"

[update]
[update.curseforge]
file-id = 3590226
project-id = 398521
