name = "Farmer's Delight"
filename = "FarmersDelight-1.18.1-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3608/555/FarmersDelight-1.18.1-1.0.2.jar"
hash-format = "murmur2"
hash = "59210431"

[update]
[update.curseforge]
file-id = 3608555
project-id = 398521
