name = "Farsight[Forge/Fabric]"
filename = "farsight-1.18-1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3604/395/farsight-1.18-1.6.jar"
hash-format = "murmur2"
hash = "879254218"

[update]
[update.curseforge]
file-id = 3604395
project-id = 495693
