name = "FerriteCore (Forge)"
filename = "ferritecore-4.0.0-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3550/45/ferritecore-4.0.0-forge.jar"
hash-format = "murmur2"
hash = "2273502909"

[update]
[update.curseforge]
file-id = 3550045
project-id = 429235
