name = "Flywheel"
filename = "flywheel-forge-1.18-0.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/401/flywheel-forge-1.18-0.5.1.jar"
hash-format = "murmur2"
hash = "1504200980"

[update]
[update.curseforge]
file-id = 3600401
project-id = 486392
