name = "FPS Reducer"
filename = "FpsReducer-forge-1.25-mc1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3548/891/FpsReducer-forge-1.25-mc1.18.jar"
hash-format = "murmur2"
hash = "3332134788"

[option]
default = true
description = "Reduces Game FPS when minized or afk"
optional = true


[update]
[update.curseforge]
file-id = 3548891
project-id = 280294
