name = "JourneyMap"
filename = "journeymap-1.18.1-5.8.0beta10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3612/223/journeymap-1.18.1-5.8.0beta10.jar"
hash-format = "murmur2"
hash = "508071462"

[update]
[update.curseforge]
file-id = 3612223
project-id = 32274
