name = "JourneyMap"
filename = "journeymap-1.18.1-5.8.0beta9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3608/899/journeymap-1.18.1-5.8.0beta9.jar"
hash-format = "murmur2"
hash = "402687476"

[update]
[update.curseforge]
file-id = 3608899
project-id = 32274
