name = "Kiwi 🥝 (Forge)"
filename = "Kiwi-1.18-forge-5.2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3623/424/Kiwi-1.18-forge-5.2.5.jar"
hash-format = "murmur2"
hash = "1167837685"

[update]
[update.curseforge]
file-id = 3623424
project-id = 303657
