name = "Konkrete [Forge]"
filename = "konkrete_forge_1.5.0_MC_1.18-1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "484e3713bcd3cf6e1303abd01325c138cffcc543"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3913001
project-id = 410295
