name = "KubeJS Create"
filename = "kubejs-create-1801.2.0-build.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3584/653/kubejs-create-1801.2.0-build.14.jar"
hash-format = "murmur2"
hash = "573652377"

[update]
[update.curseforge]
file-id = 3584653
project-id = 429371
