name = "KubeJS (Forge)"
filename = "kubejs-forge-1801.4.2-build.296.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3632/156/kubejs-forge-1801.4.2-build.296.jar"
hash-format = "murmur2"
hash = "504781936"

[update]
[update.curseforge]
file-id = 3632156
project-id = 238086
