name = "Lootr"
filename = "lootr-1.18-0.1.14.42.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3617/9/lootr-1.18-0.1.14.42.jar"
hash-format = "murmur2"
hash = "3758431861"

[update]
[update.curseforge]
file-id = 3617009
project-id = 361276
