name = "Lootr"
filename = "lootr-1.18-0.1.14.48.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3632/374/lootr-1.18-0.1.14.48.jar"
hash-format = "murmur2"
hash = "4189129548"

[update]
[update.curseforge]
file-id = 3632374
project-id = 361276
