name = "mutil"
filename = "mutil-1.18.1-4.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3612/472/mutil-1.18.1-4.2.0.jar"
hash-format = "murmur2"
hash = "1013001432"

[update]
[update.curseforge]
file-id = 3612472
project-id = 351914
