name = "No Null Processors"
filename = "no_null_processors_forge-2.0.2+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3570/790/no_null_processors_forge-2.0.2+1.18.1.jar"
hash-format = "murmur2"
hash = "1790454335"

[update]
[update.curseforge]
file-id = 3570790
project-id = 546841
