name = "Pick Up Notifier [Forge]"
filename = "PickUpNotifier-v3.1.0-1.18.1-Forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3570/56/PickUpNotifier-v3.1.0-1.18.1-Forge.jar"
hash-format = "murmur2"
hash = "1588605798"

[update]
[update.curseforge]
file-id = 3570056
project-id = 351441
