name = "Pollution of the Realms"
filename = "AdPother-1.18.2-6.0.5.0-build.1034.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "ab48ed667f98bd80de8a206c0877efe03e972fae"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3905429
project-id = 269973
