name = "Pollution of the Realms"
filename = "AdPother-1.18.2-6.0.4.0-build.0993.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "c04e519206c69bcd611609724a902c341410c435"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3860399
project-id = 269973
