name = "Puzzles Lib [Forge]"
filename = "PuzzlesLib-v3.1.3-1.18.1-Forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3583/543/PuzzlesLib-v3.1.3-1.18.1-Forge.jar"
hash-format = "murmur2"
hash = "3199367045"

[update]
[update.curseforge]
file-id = 3583543
project-id = 495476
