name = "Repurposed Structures (Forge)"
filename = "repurposed_structures_forge-4.2.2+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3611/627/repurposed_structures_forge-4.2.2+1.18.1.jar"
hash-format = "murmur2"
hash = "1843929591"

[update]
[update.curseforge]
file-id = 3611627
project-id = 368293
