name = "Repurposed Structures (Forge)"
filename = "repurposed_structures_forge-4.2.4+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3618/374/repurposed_structures_forge-4.2.4+1.18.1.jar"
hash-format = "murmur2"
hash = "557444676"

[update]
[update.curseforge]
file-id = 3618374
project-id = 368293
