name = "Repurposed Structures (Forge)"
filename = "repurposed_structures_forge-4.2.6+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3628/161/repurposed_structures_forge-4.2.6+1.18.1.jar"
hash-format = "murmur2"
hash = "3455420295"

[update]
[update.curseforge]
file-id = 3628161
project-id = 368293
