name = "Repurposed Structures (Forge)"
filename = "repurposed_structures_forge-4.2.3+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3614/155/repurposed_structures_forge-4.2.3+1.18.1.jar"
hash-format = "murmur2"
hash = "3082640743"

[update]
[update.curseforge]
file-id = 3614155
project-id = 368293
