name = "Selene Lib"
filename = "selene-1.18-1.12.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3604/965/selene-1.18-1.12.0.jar"
hash-format = "murmur2"
hash = "3162830308"

[update]
[update.curseforge]
file-id = 3604965
project-id = 499980
