name = "Simple Voice Chat"
filename = "voicechat-forge-1.18.1-2.2.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3633/30/voicechat-forge-1.18.1-2.2.17.jar"
hash-format = "murmur2"
hash = "3326963917"

[update]
[update.curseforge]
file-id = 3633030
project-id = 416089
