name = "Skin Layers 3D (Fabric/Forge)"
filename = "3dSkinLayers-forge-mc1.18-1.3.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3548/347/3dSkinLayers-forge-mc1.18-1.3.1.jar"
hash-format = "murmur2"
hash = "3368072393"

[option]
default = true
description = "Makes player skin layers 3d"
optional = true

[update]
[update.curseforge]
file-id = 3548347
project-id = 521480
