name = "Snow! Real Magic! ⛄ (Forge)"
filename = "SnowRealMagic-1.18-forge-3.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3592/132/SnowRealMagic-1.18-forge-3.0.3.jar"
hash-format = "murmur2"
hash = "3164849165"

[update]
[update.curseforge]
file-id = 3592132
project-id = 308663
