name = "Sophisticated Backpacks"
filename = "sophisticatedbackpacks-1.18.1-3.15.1.505.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3597/547/sophisticatedbackpacks-1.18.1-3.15.1.505.jar"
hash-format = "murmur2"
hash = "593528507"

[update]
[update.curseforge]
file-id = 3597547
project-id = 422301
