name = "Storage Drawers"
filename = "StorageDrawers-1.18.1-10.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3587/221/StorageDrawers-1.18.1-10.1.0.jar"
hash-format = "murmur2"
hash = "3233985665"

[update]
[update.curseforge]
file-id = 3587221
project-id = 223852
