name = "Storage Drawers"
filename = "StorageDrawers-1.18.1-10.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3611/505/StorageDrawers-1.18.1-10.1.1.jar"
hash-format = "murmur2"
hash = "341636917"

[update]
[update.curseforge]
file-id = 3611505
project-id = 223852
