name = "Supplementaries"
filename = "supplementaries-1.18.1-1.1.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3622/554/supplementaries-1.18.1-1.1.11.jar"
hash-format = "murmur2"
hash = "1423448197"

[update]
[update.curseforge]
file-id = 3622554
project-id = 412082
