name = "Supplementaries"
filename = "supplementaries-1.18.1-1.1.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3607/437/supplementaries-1.18.1-1.1.9.jar"
hash-format = "murmur2"
hash = "1923804727"

[update]
[update.curseforge]
file-id = 3607437
project-id = 412082
