name = "SwingThroughGrass"
filename = "swingthroughgrass-1.18.1-1.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3578/339/swingthroughgrass-1.18.1-1.8.0.jar"
hash-format = "murmur2"
hash = "616930588"

[update]
[update.curseforge]
file-id = 3578339
project-id = 264353
