name = "Tetra"
filename = "tetra-1.18.1-4.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3591/751/tetra-1.18.1-4.3.0.jar"
hash-format = "murmur2"
hash = "2516387983"

[update]
[update.curseforge]
file-id = 3591751
project-id = 289712
