name = "Drip Sounds (Forge)"
filename = "DripSounds-1.18-0.3.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3555/718/DripSounds-1.18-0.3.0.jar"
hash-format = "murmur2"
hash = "3887940579"

[update]
[update.curseforge]
file-id = 3555718
project-id = 390986
