# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["july-update"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.18
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            $GOPATH/bin
            $GOPATH/pkg
            /opt/buildhome/.cache/packwiz/cache
          key: ${{ runner.os }}-go
          restore-keys: |
            ${{ runner.os }}-go
            
      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest
        
      - name: Generate subfolders
        run: mkdir ./builds

      - name: generate curseforge modpack
        run: packwiz curseforge export --side client -o ./builds/curseforge.zip
        
      - name: generate modrinth modpack
        run: packwiz modrinth export -o ./builds/modrinth.mrpack
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'

#       - name: generate server curseforge modpack
#         run: packwiz curseforge export --side server 
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
